### ISSUE TITLE
DATASET:vmrdcompv1

### ISSUE THREAD

**Issue by WuXingrui** [ZhangHanbo/Visual-Manipulation-Relationship-Network-Pytorch#1]
Hi @ZhangHanbo ,I'm trying to run this code,where can I get the vmrdcompv1 dataset?

**Comment by ZhangHanbo** [comment]
The link is included in the papers. 

> Hi @ZhangHanbo ,I'm trying to run this code,where can I get the vmrdcompv1 dataset?

**Comment by WuXingrui** [comment]
Got it! Thanks!

**Comment by WHGang** [comment]
> Got it! Thanks!

你好，我也在学习机器人虎抓取方面的东西。我们可以有问题一起讨论下。方便的话加个微信吧：18810893603，有问题一起讨论，一起学习

**Comment by WHGang** [comment]
> Got it! Thanks!

你好，我也在学习机器人虎抓取方面的东西。我们可以有问题一起讨论下。方便的话加个微信吧：18810893603，有问题一起讨论，一起学习
