### ISSUE TITLE
Manipulation relationship tree

### ISSUE THREAD

**Issue by WuXingrui** [ZhangHanbo/Visual-Manipulation-Relationship-Network-Pytorch#2]
Besides the accuary, how could i see the manipulation relationship result by the Manipulation relationship tree? I don't know how to get it.
Hope to get some help. Thanks!

**Comment by Lind592** [comment]
how could i see the manipulation relationship result by the Manipulation relationship tree? I don't know how to get it.
Hope to get some help. Thanks!

**Comment by Lind592** [comment]
> Besides the accuary, how could i see the manipulation relationship result by the Manipulation relationship tree? I don't know how to get it.
> Hope to get some help. Thanks!

请问你有办法解决生成操作关系树吗？
是否有类似的demo？

**Comment by ZhangHanbo** [comment]
> how could i see the manipulation relationship result by the Manipulation relationship tree? I don't know how to get it.
> Hope to get some help. Thanks!

Hello! In fact, the generation of manipulation relationship tree is not included in the current version.

Since I have been busy with something else, the code has not been updated since it is uploaded.

I am working on it now, including reconstructing the code structure, completing all the related details (e.g. manipulation relationship tree) and implementing some state-of-the-art algorithms that may help to improve the performance.

Thanks for your interests!

**Comment by ZhangHanbo** [comment]
> Besides the accuary, how could i see the manipulation relationship result by the Manipulation relationship tree? I don't know how to get it.
> Hope to get some help. Thanks!

Hello! In fact, the generation of manipulation relationship tree is not included in the current version.

Since I have been busy with something else, the code has not been updated since it is uploaded.

I am working on it now, including reconstructing the code structure, completing all the related details (e.g. manipulation relationship tree) and implementing some state-of-the-art algorithms that may help to improve the performance.

Thanks for your interests!

**Comment by ZhangHanbo** [comment]
> Besides the accuary, how could i see the manipulation relationship result by the Manipulation relationship tree? I don't know how to get it.
> Hope to get some help. Thanks!

If you do not mind, I can provide you a draft for generating manipulation relationship tree, which was used in the robotic experiments when I submit the paper to IROS.

**Comment by ZhangHanbo** [comment]
> > Besides the accuary, how could i see the manipulation relationship result by the Manipulation relationship tree? I don't know how to get it.
> > Hope to get some help. Thanks!
> 
> 请问你有办法解决生成操作关系树吗？
> 是否有类似的demo？

If you do not mind, I can provide you a draft for generating manipulation relationship tree, which was used in the robotic experiments when I submit the paper to IROS.

**Comment by Lind592** [comment]
Thank you for your reply.
I need a draft for generating manipulation relationship tree.
May I ask if this draft can generate the manipulation relationship tree&nbsp;after inputting the image？

I am very grateful&nbsp;If you can provide a demo or instruction manual.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Hanbo Zhang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月11日(星期三) 晚上9:34
收件人:&nbsp;"ZhangHanbo/Visual-Manipulation-Relationship-Network-Pytorch"<Visual-Manipulation-Relationship-Network-Pytorch@noreply.github.com&gt;;
抄送:&nbsp;"Lind"<530413240@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [ZhangHanbo/Visual-Manipulation-Relationship-Network-Pytorch] Manipulation relationship tree (#2)





   
Besides the accuary, how could i see the manipulation relationship result by the Manipulation relationship tree? I don't know how to get it.
 Hope to get some help. Thanks!
  
请问你有办法解决生成操作关系树吗？
 是否有类似的demo？
  
If you do not mind, I can provide you a draft for generating manipulation relationship tree, which was used in the robotic experiments when I submit the paper to IROS.

**Comment by Lind592** [comment]
Thank you for your reply.

I am very grateful If you can provide me a draft for generating manipulation relationship tree, which was used in the robotic experiments&nbsp;.










------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Hanbo Zhang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月11日(星期三) 晚上9:34
收件人:&nbsp;"ZhangHanbo/Visual-Manipulation-Relationship-Network-Pytorch"<Visual-Manipulation-Relationship-Network-Pytorch@noreply.github.com&gt;;
抄送:&nbsp;"Lind"<530413240@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [ZhangHanbo/Visual-Manipulation-Relationship-Network-Pytorch] Manipulation relationship tree (#2)





  
Besides the accuary, how could i see the manipulation relationship result by the Manipulation relationship tree? I don't know how to get it.
 Hope to get some help. Thanks!
  
If you do not mind, I can provide you a draft for generating manipulation relationship tree, which was used in the robotic experiments when I submit the paper to IROS.

**Comment by Lind592** [comment]
Can you provide me a draft for generating manipulation relationship tree, which was used in the robotic experiments when I submit the paper to IROS.

Hope to get some help. Thanks

**Comment by Lind592** [comment]
Can you provide me a draft for generating manipulation relationship tree, which was used in the robotic experiments when you submit the paper to IROS.

Hope to get some help. Thanks

**Comment by ZhangHanbo** [comment]
> Can you provide me a draft for generating manipulation relationship tree, which was used in the robotic experiments when you submit the paper to IROS.
> 
> Hope to get some help. Thanks

I cannot go back to school now, and the related code is stored in the experimental computer. Once I go back to school, i will send you the draft code.

**Comment by Lind592** [comment]
Thank you for your help
If you can find this draft code, please send it to me as soon as possible
I really need this code.
In addition, Do you have a demo for the actual robot ?

**Comment by ZhangHanbo** [comment]
> Thank you for your help
> If you can find this draft code, please send it to me as soon as possible
> I really need this code.
> In addition, Do you have a demo for the actual robot ?

See my YouTube

**Comment by Lind592** [comment]
你好，现在在得到 det_rel = np.argmax(det_rel_prob, 1) + 1后，如何求得操作分数对应哪两个物体。
我看test中是用
b1_gt = np.argmax(match_mat[b1])
b2_gt = np.argmax(match_mat[b2])
rel_gt = rel_mat_gt[b1_gt, b2_gt]
if rel_gt == det_rel[rel_ind]:
tp += 1
得到分数对应的两个物体。
请问实际输入一张图像上 如何将分数对应到相应的物体中？

**Comment by ZhangHanbo** [comment]
> Thank you for your help
> If you can find this draft code, please send it to me as soon as possible
> I really need this code.
> In addition, Do you have a demo for the actual robot ?

The visualization code has been already updated.
