### ISSUE TITLE
Question about downloading VMRD dataset

### ISSUE THREAD

**Issue by xjtAlgo** [ZhangHanbo/Visual-Manipulation-Relationship-Network-Pytorch#6]
The dataset resource download URL http://gr.xjtu.edu.cn/web/zeuslan/visual-manipulation-relationshipdataset of the paper has disappeared. The website indicates that the resource can not be found.
Could you re-upload the VMRD dataset resource，thank you.
Or hope that a partner who has VMRD dataset will share it with me,thanks again.

**Comment by Zixin-Tang** [comment]
Hi @xjtAlgo, have you downloaded the VMRD dataset successfully?
